# Generated by Django 4.2.30 on 2026-04-09
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_time_limited',
            field=models.BooleanField(default=True, help_text='是否启用考试时间限制', verbose_name='是否限时'),
        ),
    ]
